/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export { GAINUSDTDistributor__factory } from "./GAINUSDTDistributor__factory";
