openapi: 3.0.3
info:
  title: GAIN-USDT Backend API
  version: 1.1.0
servers:
  - url: http://localhost:4000
paths:
  /health:
    get:
      summary: Service health & network
      responses:
        "200":
          description: Service health
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  chain:
                    type: string
                  usdtToken:
                    type: string
  /config:
    get:
      summary: Distributor configuration snapshot
      responses:
        "200":
          description: Distributor configuration
          content:
            application/json:
              schema:
                type: object
                properties:
                  chain:
                    type: string
                  contract:
                    type: object
                    properties:
                      address:
                        type: string
                  usdtToken:
                    type: string
                  tokenDecimals:
                    type: integer
                  creatorWallet:
                    type: string
                  flashWallet:
                    type: string
                  slotPrices:
                    type: array
                    items:
                      type: string
                  royaltyBps:
                    type: object
                    additionalProperties:
                      type: integer
  /user/{address}:
    get:
      summary: Fetch user profile data
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Profile information
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  referrer:
                    type: string
                  maxSlot:
                    type: integer
                  registeredAllowance:
                    type: object
                    properties:
                      allowance:
                        type: string
                      blockNum:
                        type: integer
                  qualifiedDirects:
                    type: array
                    items:
                      type: object
                      properties:
                        level:
                          type: integer
                        count:
                          type: integer
        "400":
          description: Invalid address
  /admin/set-creator-wallet:
    post:
      summary: Update creator wallet
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet:
                  type: string
      responses:
        "200":
          description: Transaction receipt
  /admin/set-flash-wallet:
    post:
      summary: Update flash wallet
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet:
                  type: string
      responses:
        "200":
          description: Transaction receipt
  /admin/pause:
    post:
      summary: Pause the contract
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Transaction receipt
  /admin/unpause:
    post:
      summary: Unpause the contract
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Transaction receipt
  /admin/withdraw-usdt:
    post:
      summary: Withdraw USDT (FUNDS_ROLE)
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                amount:
                  type: string
      responses:
        "200":
          description: Transaction receipt
  /admin/recover-token:
    post:
      summary: Recover arbitrary ERC20 (FUNDS_ROLE)
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                to:
                  type: string
                amount:
                  type: string
      responses:
        "200":
          description: Transaction receipt
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
